#page title
page_title: Q.ai - Questions? Ask Q.ai!  # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 6447635159 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=ai.cybercat.mindpilot
presskit_download_link: # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Q.ai # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Questions? Ask Q.ai! # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: "From writing stories and essays, to answering any question you have, <br/>Q.ai can do it all!"

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: CyberCat
your_link: 
your_city: 
email_address: cybercat.ai@gmail.com
facebook_username:
instagram_username: 
twitter_username: zubin_tang
github_username: qdotai
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: One-tap-chat Experience
    description: Chatting to an AI has never been so SLEEK.
    fontawesome_icon_name: comments

  - title: Inspirational Design
    description: Doubles the inspiration in every conversation
    fontawesome_icon_name: lightbulb

  - title: All-Knowing AI Assistant
    description: Unleashing limitless knowledge, answering all your questions on any topic. Science, emotions, career, and lifestyle, and more.
    fontawesome_icon_name: brain

  - title: Versatile writing assistant
    description: Helps you craft perfect emails, blogs, Instagram and tweets.
    fontawesome_icon_name: pencil-alt

  - title: Language master
    description: Providing flawless translation, summarization, and rewriting in 140+ languages
    fontawesome_icon_name: language

  - title: Markdown & LaTex Support
    description: Making every message in beautiful format
    fontawesome_icon_name: code

# Theme Settings
topbar_color: '#000000'
topbar_transparency: 0.0
topbar_title_color: '#ffffff'

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: '#363b3d'
cover_overlay_transparency: 0.0

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: '#ffffff'

link_color: '#1d63ea'

app_title_color: '#ffffff'
app_price_color: '#ffffff'
app_description_color: '#ffffff'

feature_title_color: '#000000'
feature_text_color: '#666666'

feature_icons_foreground_color: '#1d63ea'
feature_icons_background_color: '#e6e6e6'

social_icons_foreground_color: '#666666'
social_icons_background_color: '#e6e6e6'

footer_text_color: '#666666'

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
kramdown:
  parse_block_html: true
